---
title: "dataProject_v1"
output: html_document
---
```{r}
library(httr)
library(httr2)
library(curl)
library(R.utils)
library(data.table)    
library(dplyr)
#install.packages("tidyverse")
library(tidyverse)
```

```{r}

  # Brugeren inputter én eller flere tnames i load_case, f.eks. c(BIS/EMG, Primus/INSP_DES, Solar8000/BT)
  # Brugeren inputter også ét (og kun ét) case id. f.eks. "17"
  # Funktionen samler nu alle "tids" forbundet med de forskellige tnames i case 1. ( i det her tilfælde 3 stk.)
  # Funktionen kalder nu load_trks(tids), der kalder load_trk(tid) som kalder load vdb (der henter fra api) på alle tid i tids
  # dermed bliver der returnet 3 tidsserier c(BIS/EMG, Primus/INSP_DES, Solar8000/BT), der alle tilhører case 17

load_VDB <- function(file_url) {
  con <- gzcon(url(file_url))
  txt <- readLines(con)
  return(read.csv(textConnection(txt)))
}

load_trk <- function(tid, interval){
  start <- "https://api.vitaldb.net/"
  end <- ".csv.gz" 
  # start + tid + end
  url <- paste(start, tid, end, sep="")
  df = load_VDB(url)
  df$Time <- df$Time/interval
  df$Time[3] <- NaN
  
  nsamp <- nrow(!is.na(df))
  #View(nsamp)
  #View(df$Time)
  
  ret = data.frame(matrix(ncol=1, nrow=nsamp, NaN))
  
  #View(df$Time)
  if(any(is.na(df$Time))){
    print("if")
    
    if(nsamp != length(df$Time)){
      print("if3")
      interval <- seq(from = 0, to = length(df$Time), by = nsamp)
      ret <- df$Time[interval]
    }
    else{
      print("else2")
      ret <- df[,2]
    }
  }
  else{
    print("else")
  }
  return(df)
}

load_trks <- function(tids){
  data <- data.frame()
  index <- 1
  for (i in 1:nrow(tids)){
    load_trk(tids[i,])
    index <- index+1
  }
}

load_case <- function(tnames, caseid){
  tracks <- load_VDB("https://api.vitaldb.net/trks.csv.gz")
  tracks <- tracks[tracks$caseid == caseid,]
  tids <- data.frame(col = rep(NA, length(tnames)))
  index <- 1
  for (tname in tnames){
    tids$col[index] <- (tracks[tracks$tname == tname,])$tid
    index <- index+1
  }
  load_trks(tids)
}

#load_case(c("BIS/EMG","Solar8000/BT"), 1)
load_trk("0cb17dee113443b52e3d71b55e3be170d5f60117",10)



```

```{r}
#url <- "https://api.vitaldb.net/afd182c102c5af625d3f217280b3766d453d9e3f.csv.gz"
url2 <- "https://api.vitaldb.net/trks.csv.gz"
url3 <- "https://api.vitaldb.net/cases.csv.gz"
url4 <- "https://api.vitaldb.net/labs.csv.gz"

#loading track data
trackdata <- load_VDB(url)
# loading tracks
tracks <- load_VDB(url2)
# loading cases
cases <- load_VDB(url3)
# loading labs
labs <- load_VDB(url4)
```

```{r}
closeAllConnections()
```

