---
title: "Gam Experiments"
author: "Georg"
date: "3/1/2022"
output: pdf_document
---
Installing MGCV
If you have trouble installing on mac, download source from https://cran.r-project.org/web/packages/mgcv/index.html and run a terminal with "R CMD INSTALL packagename.tgz"
```{r}
#install.packages("mgcv")
library("mgcv")
help("mgcv-package")
```

Installing gratia
```{r}
#install.packages("gratia")
library("gratia")
#??gratia
```

```{r}
#install.packages("patchwork")
library("patchwork")
#??patchwork
```

We should perhaps implement a function, so that we don't need to import accelrometry
```{r}
#install.packages("accelerometry")
<<<<<<< .merge_file_a19180
library("accelerometry")
```

```{r}
library("dplyr")
library("ggplot2")
=======
library(accelerometry)
library(ggplot2)
```


```{r}
#install.packages("purrr")
library("purrr")
```



```{r}
source("functions.R")
sample_pp <-readRDS("sample_PP.RDS")
beats <- find_abp_beats(sample_pp$abp)
head(beats)
```

```{r}
abp_plot <- ggplot(sample_pp$abp, aes(time, ABP)) +
geom_line() +
geom_vline(aes(xintercept = time), color = "red",
data = sample_pp$insp_start)
abp_plot


abp_plot +
geom_point(aes(x = time,
y = dia,
colour = "diastole"),
data = beats) +
geom_point(aes(x = time_systole,
y = sys,
colour = "systole"),
data = beats)
```


```{r}
beats_indexed <- add_time_since_event(beats,
time_events = sample_pp$insp_start$time,
prefix = "insp") %>%
# the first beats are earlier than the first inspiration and
# therefore have `insp_rel_index = NA`. We remove these.
na.omit()
# Show only time and

PP_gam <- gam(
# The first parameter to the gam() function is the model specification,
# supplied using formula notation:
PP ~ # Left of the tilde (~) is our dependent variable PP
# Right of the tilde is our independent variables.
# Define a smooth function of insp_rel_index.
s(insp_rel_index,
k = 15, # 15 knots.
bs = "cc" # The basis is a cyclic cubic spline
) +
# Define a smooth function of time
s(time,
bs = "cr" # The basis is a natural cubic spline.
# default k is 10. This will be fine here.
),
# We can specify the positions of the knots for each smooth.
# If only two knots are specified for a cyclic spline, these will
# set the positions of the limiting knot(s). The remaining knots will
# be positioned automatically (at quantiles).
knots = list(insp_rel_index = c(0,1)),
# We use restricted maximum likelihood (REML) to fit the optimal smoothing parameter.
# This is often the best choice, but not the default.
method = "REML",
data = PP_data
)
>>>>>>> .merge_file_a08548
```

