---
title: "Heartbeat from Art"
author: "Georg"
date: "4/6/2022"
output: pdf_document
---

Importing VitalDBR
```{r}
library(devtools)
install_github('legendenomgeorg/VitalDBR/VitalDBR')
library(VitalDBR)
library(waveformtools)
```

Loading in data
```{r}
df <- load_case('SNUADC/ART', 1)
```

```{r}
df <- ts(df,frequency = 500) # Det her gør funktionen nu, men den er ikke blevet pushet

```



```{r}
#cleaning
sub <- window(df,1000,1010)
sub <- data.frame(sub)
sub <- cbind(sub,"Time"=1:nrow(sub))
plot(sub$Time, sub$SNUADC.ART,type='l')
sub

```
Lav algortime der finder starttidspunkter (lige der hvor den riser)

```{r}
#signal:
sub <- filter_signal(sub,25,1,500)
peaks <- find_peaks(sub$SNUADC.ART_filt,m=1)
dips <- find_peaks(-sub$SNUADC.ART_filt,m=1)
plot(sub$Time, sub$SNUADC.ART, type='l')
for (x in peaks){
  abline(v=x,col="blue")
  
}
for (x in dips){
  abline(v=x,col="red")
  
}
```

```{r}
plot(sub$Time, sub$SNUADC.ART, type='l')
plot(sub$Time, sub$SNUADC.ART_filt, type='l')
```
```{r}
#find_abp_beats(sub, 1, 2, sample_rate=500 ) #Virker hvis vi laver tid om til sekunder
head(sub)
```

