---
title: "Inspiration from AWP"
author: "Georg"
date: "4/19/2022"
output: html_document
---

```{r}
remotes::install_github("https://github.com/JohannesNE/waveformtools")
```


Importing VitalDBR
```{r}
library(devtools)
install_github('legendenomgeorg/VitalDBR/VitalDBR')
library(VitalDBR)
#install.packages("gsignal")
library(gsignal)
library(stats)
library(waveformtools)
```

Loading in data
```{r}
df <- load_case('Primus/AWP', 1)

```

```{r}
df

```
```{r}
plot(df, type="l")
```
```{r}
#Dropper lige outlier detection
#library("forecast")
#y <- tsoutliers(ts(df$Primus.AWP), iterate = 2, lambda = "auto")
#df[y$index,2] = y$replacements

```
```{r}
plot(df, type='l')
```


```{r}
sek <- 200
start <- 490000
sub<- df[start:(start+(sek*62.5)),] #  10 sekunder fra 10000 (cirka 625 observationer)
#sub <- filter_signal(sub, 25,2,300) # Burde være 62.5 istedet for 1000, men der sker ikke rigtig noget med waveformen
#par(mfrow=c(1,2))
plot(sub$Time, sub$Primus.AWP, type='l')
#plot(sub$Time, sub$Primus.AWP_filt, type='l')


```
```{r}
#sub$Primus.AWP
n = 6
before <- rep(1, n)
after <- rep(-1, n)

my_filter <- c(before, 0, after)
my_filter
conv1 <- data.frame(as.matrix(stats::filter(x = sub$Primus.AWP, filter= my_filter, sides=1, method="convolution")))
conv1 <- cbind(conv1,sub$Time)

conv1 <- conv1[, c(2,1)]
names(conv1)[1] <- "Time"
names(conv1)[2] <- "Values"
conv1 <- waveformtools::filter_signal(conv1, 25, 2000, signal_col = 2)
peaks <- waveformtools::find_peaks(conv1$Values_filt,m=100, na.ignore=TRUE)
peaks <- conv1$Time[peaks]
peaks <- peaks[2:length(peaks)] # removing the first peak since it is not representative
par(mfrow=c(2,1))
plot(conv1$Time, conv1$Values_filt, type='l')
for (x in peaks){
  abline(v=x,col="blue")
}
plot(sub$Time,sub$Primus.AWP, type='l')
for (x in peaks){
  abline(v=x,col="blue")
}

```








```{r}

#Convolve step
conv1 <- data.frame(convolve(sub$Time,sub$Primus.AWP, type="circular" ))
conv1 <- cbind(conv1,sub$Time)
conv1 <- conv1[, c(2,1)]
names(conv1)[1] <- "Time"
names(conv1)[2] <- "Values"
conv1$Values
peaks <- gsignal::findpeaks(conv1$Values)
peaks <- conv1$Time[peaks$loc]
par(mfrow=c(2,1))
plot(conv1$Time, conv1$Values, type='l')
for (x in peaks){
  abline(v=x,col="blue")
}
plot(sub$Time,sub$Primus.AWP, type='l')
for (x in peaks){
  abline(v=x,col="blue")
}

```






