---
title: "Inspiration from AWP"
author: "Georg"
date: "4/19/2022"
output: html_document
---

Importing VitalDBR
```{r}
library(devtools)
install_github('legendenomgeorg/VitalDBR/VitalDBR')
library(VitalDBR)
```

Loading in data
```{r}
df <- load_case('Primus/AWP', 1)

```

```{r}
plot(df)
```
```{r}
tisek<- df[100000:(100000+(100*62.5))] #  10 sekunder fra 10000 (cirka 625 observationer)
plot(tisek, type='l')
abline(v = 267)
abline(v=580)
abline(v=893)
```

```{r}

#peaks = c()

for(i in 1:(length(df)-1)){
  diff <- df[i+1] - df[i]
  #print(diff)
  if(diff > 1){
    #append(peaks, i)
  }
}
```

```{r}

myFunc <- function(df, sensitivity){
peaks = rep(NA, length(df))

for(i in 1:(length(df)-1)){
  diff <- df[i+1] - df[i]
  #print(diff)
  if(diff > sensitivity){
    #print(i)
    peaks[i] <- i
  }
}
  return(peaks[!is.na(peaks)])
}
```


```{r}
length(df)
```

```{r}
peaksSorted <-peaks[!is.na(peaks)]
```


```{r}
sek <- 10
tisek<- df[105200:(105200+(sek*62.5))] #  10 sekunder fra 10000 (cirka 625 observationer)

peaks <- myFunc(tisek, 0.9)
plot(tisek, type='l')
for(i in 1:length(peaks)){
  abline(v=peaks[i], col = 'red')
}
```



