---
title: "dataProject_v1"
output: html_document
---

```{r}
  # Brugeren inputter én eller flere tnames i load_case, f.eks. c(BIS/EMG, Primus/INSP_DES, Solar8000/BT)
  # Brugeren inputter også ét (og kun ét) case id. f.eks. "17"
  # Funktionen samler nu alle "tids" forbundet med de forskellige tnames i case 1. ( i det her tilfælde 3 stk.)
  # Funktionen kalder nu load_trks(tids), der kalder load_trk(tid) som kalder load vdb (der henter fra api) på alle tid i tids
  # dermed bliver der returnet 3 tidsserier c(BIS/EMG, Primus/INSP_DES, Solar8000/BT), der alle tilhører case 17
  # NOTE fungerer ikke helt sådan her længere, vi kan ikke loade flere tnames

load_VDB <- function(file_url) {
  con <- gzcon(url(file_url))
  txt <- readLines(con)
  return(read.csv(textConnection(txt)))
}

check_hz <- function(df){
  if (is.na(df[1,2]) & is.na(df[2,2] & !is.na(df[1,1]) & !is.na(df[2,1]) )){
    freq = df[2,1]
    df <- subset (df, select = -Time)
    df<- na.omit(df)
    df <- cbind(df,"Time"=1:nrow(df)*freq)
    df <- df[, c(2,1)] # reorder columns
    return(df)
  }
  else {
    return(df)
  }
}

load_trk <- function(tid){
  start <- "https://api.vitaldb.net/"
  end <- ".csv.gz" 
  # start + tid + end
  url <- paste(start, tid, end, sep="")
  df = load_VDB(url)
  return(check_hz(df))
}

load_case <- function(tname, caseid){
  tracks <- load_VDB("https://api.vitaldb.net/trks.csv.gz")
  tracks <- tracks[tracks$caseid == caseid,]
  tid <- (tracks[tracks$tname == tname,])$tid
  load_trk(tid)
}

# a function that subsets a timeseries from input in seconds.
subset_ts <- function(ts,start_sec, end_sec) {
  return(window(ts,start,end))
}


df<-load_case("Primus/AWP", 1)

```

```{r}
df

```


```{r}
load_VDB("https://api.vitaldb.net/fd869e25ba82a66cc95b38ed47110bf4f14bb368")
```

